Give extra architecture information
hpi-sam/sct-validation-framework pull request #1
Opened 2022-09-28 08:57 UTC by SimonWiet

Adds the architecture diagram and some more detailed description on how to set up a world

2022-10-12 15:42 UTC, christianschaeffer requested changes
Generally this looks good. I proposed some typo fixes however. 

Also, please make sure you write "statechart" consistently as one word (as in the paper). I read a lot of "state chart". Thanks!

2022-10-12 15:42 UTC, christianzoellner commented on README.md
> +   - When there is the need to add/edit static parameters (magic numbers), do so by extending the class `core.Configuration`
```suggestion
   - When you need to overwrite and/or add static parameters (magic numbers), do so by adding a class that extends `core.Configuration` in your `world` subpackage.

```

2022-10-13 08:30 UTC, SimonWiet commented
Valid comments, I commited them and additionally renamed some occurences of "state chart(s)" to "statechart(s)"

2022-10-14 17:15 UTC, christianzoellner approved these changes
Thanks for resolving my previous comments and for your work on the text @SimonWiet!

2022-11-18 15:17 UTC, merged